package noppes.mpm.constants;

public enum EnumPackets {
     PING,
     SEND_PLAYER_DATA,
     UPDATE_PLAYER_DATA,
     CHAT_EVENT,
     BACK_ITEM_REMOVE,
     BACK_ITEM_UPDATE,
     PARTICLE,
     ANIMATION,
     EYE_BLINK,
     PROP_ADD,
	 PROP_REMOVE,
	 PROP_SYNC,
     PROP_CLEAR,
	 PROP_GUI_OPEN,
	 PROP_GIVE,
	 PROP_HIDE,
	 PROP_SHOW,
	 PROP_NAME,
	 PROPGROUP_GIVE,
	 PROPGROUP_SHOW,
	 PROPGROUP_HIDE,
	 PROPGROUP_ADD,
	 PROPGROUP_REMOVE,
	 PROPGROUP_SAVE;
}
