package noppes.mpm.constants;

public enum EnumPackets {
     PING,
     SEND_PLAYER_DATA,
     UPDATE_PLAYER_DATA,
     CHAT_EVENT,
     BACK_ITEM_REMOVE,
     BACK_ITEM_UPDATE,
     PARTICLE,
     ANIMATION,
     EYE_BLINK,
     PROP_ITEM_UPDATE,
     PROP_PART_UPDATE,
     PROP_SCALEX_UPDATE,
     PROP_SCALEY_UPDATE,
     PROP_SCALEZ_UPDATE,
     PROP_OFFSETX_UPDATE,
     PROP_OFFSETY_UPDATE,
     PROP_OFFSETZ_UPDATE,
     PROP_ROTATEX_UPDATE,
     PROP_ROTATEY_UPDATE,
     PROP_ROTATEZ_UPDATE,
	 PROP_AUTOSCALE_UPDATE,
     PROP_CLEAR,
	 PROP_REMOVE,
	 PROP_GUI_OPEN,
	 PROP_GIVE;
}
